"""AgentForge Core Runtime Engine.

Universal runtime engine providing agent adapter abstractions, SSE streaming,
thread-safe database persistence, structured JSON logging, and configuration.
Designed to run standalone when copied into backend/src/core/.
"""

from .adapter import (
    AdapterConfigurationError,
    AdapterError,
    AdapterExecutionError,
    AdapterTimeoutError,
    AgentChunk,
    AgentEventType,
    AgentInput,
    AgentMessage,
    AgentOutput,
    AgentRole,
    AutoGenAdapter,
    BaseAgentAdapter,
    BedrockAdapter,
    CrewAIAdapter,
    DeepAgentAdapter,
    GoogleGenAIAdapter,
    InterruptRequiredError,
    InvalidInputError,
    LangChainAdapter,
    LangGraphAdapter,
    LlamaIndexAdapter,
    ToolCall,
    ToolDefinition,
    ToolResult,
    get_adapter,
)
from .config import BaseAppSettings, get_settings
from .database import (
    ConnectorError,
    Database,
    DatabaseConnectionError,
    DatabaseError,
    DatabasePoolTimeoutError,
    DBClient,
    DualAsyncSessionContext,
    DualSyncSessionContext,
    Page,
    PageMetadata,
    PageableParams,
    apaginate,
    apply_pageable_params,
    db,
    get_async_session,
    get_pk_list,
    get_pk_values,
    get_session,
    paginate,
)
from .logging import (
    CorrelationIdFilter,
    JsonFormatter,
    get_correlation_id,
    reset_correlation_id,
    set_correlation_id,
    setup_logger,
)
from .streaming import RuntimeContext, SSETokenStreamer

__all__ = [
    # 1. Agent Adapter Interface & Chunk Events
    "BaseAgentAdapter",
    "AgentChunk",
    "AgentEventType",
    "AgentRole",
    "AgentMessage",
    "AgentInput",
    "AgentOutput",
    "ToolDefinition",
    "ToolCall",
    "ToolResult",
    "AdapterError",
    "AdapterConfigurationError",
    "AdapterExecutionError",
    "InvalidInputError",
    "InterruptRequiredError",
    "AdapterTimeoutError",
    "LangChainAdapter",
    "LlamaIndexAdapter",
    "GoogleGenAIAdapter",
    "CrewAIAdapter",
    "AutoGenAdapter",
    "LangGraphAdapter",
    "DeepAgentAdapter",
    "BedrockAdapter",
    "get_adapter",
    # 2. Streaming Engine & Runtime Governance
    "SSETokenStreamer",
    "RuntimeContext",
    # 3. Database & Pagination
    "Database",
    "DBClient",
    "db",
    "DatabaseError",
    "DatabaseConnectionError",
    "DatabasePoolTimeoutError",
    "ConnectorError",
    "DualSyncSessionContext",
    "DualAsyncSessionContext",
    "get_session",
    "get_async_session",
    "Page",
    "PageMetadata",
    "PageableParams",
    "apply_pageable_params",
    "paginate",
    "apaginate",
    "get_pk_list",
    "get_pk_values",
    # 4. Logging & Observability
    "setup_logger",
    "JsonFormatter",
    "CorrelationIdFilter",
    "get_correlation_id",
    "set_correlation_id",
    "reset_correlation_id",
    # 5. Configuration Management
    "BaseAppSettings",
    "get_settings",
]
