"""agentforge/core/adapter.py

Unified Agent Adapter Layer for AgentForge.
Provides standardized message models, streaming event types, exception hierarchy,
and normalized adapters across 8 major AI agent frameworks.
"""

from __future__ import annotations

import asyncio
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from enum import Enum
import json
import logging
from typing import Any, AsyncGenerator, Dict, List, Optional, Union
import uuid

from pydantic import BaseModel, ConfigDict, Field

logger = logging.getLogger(__name__)


# ============================================================================
# 1. Core Enums & Data Contracts
# ============================================================================

class AgentEventType(str, Enum):
    """Normalized event types for real-time agent streaming."""
    TOKEN = "token"          # Incremental text token
    EVIDENCE = "evidence"    # Grounding, citations, tool outputs, retrieved documents
    META = "meta"            # Metadata (model name, latency, token usage, thought traces)
    INTERRUPT = "interrupt"  # Human-in-the-loop (HITL) approval pause gate
    ERROR = "error"          # Runtime, upstream, or validation error
    DONE = "done"            # Stream completion terminal indicator


class AgentRole(str, Enum):
    """Normalized participant roles in agent conversations."""
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"
    FUNCTION = "function"


class ToolDefinition(BaseModel):
    """Normalized tool specification schema."""
    name: str
    description: str
    parameters: Dict[str, Any] = Field(default_factory=dict)

    model_config = ConfigDict(populate_by_name=True, from_attributes=True)

    def to_dict(self) -> Dict[str, Any]:
        if hasattr(self, "model_dump"):
            return self.model_dump()
        return self.dict()


class ToolCall(BaseModel):
    """Normalized tool call request generated by an agent."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    arguments: Dict[str, Any] = Field(default_factory=dict)

    model_config = ConfigDict(populate_by_name=True, from_attributes=True)

    def to_dict(self) -> Dict[str, Any]:
        if hasattr(self, "model_dump"):
            return self.model_dump()
        return self.dict()


class ToolResult(BaseModel):
    """Normalized execution result of a tool call."""
    tool_call_id: str
    name: str
    content: str
    is_error: bool = False

    model_config = ConfigDict(populate_by_name=True, from_attributes=True)

    def to_dict(self) -> Dict[str, Any]:
        if hasattr(self, "model_dump"):
            return self.model_dump()
        return self.dict()


class AgentMessage(BaseModel):
    """Normalized conversation message representation."""
    role: AgentRole = AgentRole.USER
    content: str = ""
    name: Optional[str] = None
    tool_call_id: Optional[str] = None
    tool_calls: Optional[List[Dict[str, Any]]] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)

    model_config = ConfigDict(populate_by_name=True, from_attributes=True)

    def to_dict(self) -> Dict[str, Any]:
        res = self.model_dump() if hasattr(self, "model_dump") else self.dict()
        res["role"] = self.role.value if isinstance(self.role, Enum) else str(self.role)
        return res


class AgentInput(BaseModel):
    """Standardized input payload passed to BaseAgentAdapter."""
    prompt: Optional[str] = None
    messages: List[AgentMessage] = Field(default_factory=list)
    session_id: Optional[str] = None
    chat_id: Optional[str] = None
    turn_id: Optional[str] = None
    tools: Optional[List[ToolDefinition]] = None
    config: Dict[str, Any] = Field(default_factory=dict)
    resume_payload: Optional[Dict[str, Any]] = None

    model_config = ConfigDict(populate_by_name=True, from_attributes=True)

    def get_prompt_or_last_message(self) -> str:
        """Extract prompt text or fallback to the latest user message content."""
        if self.prompt is not None and self.prompt.strip():
            return self.prompt.strip()
        for msg in reversed(self.messages):
            if (msg.role == AgentRole.USER or str(msg.role) == "user") and msg.content and msg.content.strip():
                return msg.content.strip()
        return ""


class AgentOutput(BaseModel):
    """Standardized output payload returned by BaseAgentAdapter.ainvoke."""
    content: str = ""
    messages: List[AgentMessage] = Field(default_factory=list)
    tool_calls: List[ToolCall] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    turn_id: Optional[str] = None
    finish_reason: Optional[str] = None

    model_config = ConfigDict(populate_by_name=True, from_attributes=True)

    def to_dict(self) -> Dict[str, Any]:
        if hasattr(self, "model_dump"):
            return self.model_dump()
        return self.dict()


class AgentChunk(BaseModel):
    """
    Standardized stream chunk yielded during real-time streaming.
    Supports both `event` and `type` property access for complete contract compatibility.
    """
    event: AgentEventType = AgentEventType.TOKEN
    data: Union[Dict[str, Any], str, None] = None
    content: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)
    error: Optional[str] = None
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    id: Optional[str] = None

    model_config = ConfigDict(populate_by_name=True, from_attributes=True)

    def __init__(self, **data_kw: Any) -> None:
        # Support initializing with 'type' as alias for 'event'
        if "type" in data_kw and "event" not in data_kw:
            data_kw["event"] = data_kw.pop("type")
        super().__init__(**data_kw)

    @property
    def type(self) -> AgentEventType:
        """Alias for event type compatibility."""
        return self.event

    def to_dict(self) -> Dict[str, Any]:
        """Pydantic v1 / v2 compatible dictionary serialization."""
        res = self.model_dump() if hasattr(self, "model_dump") else self.dict()
        event_str = self.event.value if isinstance(self.event, Enum) else str(self.event)
        res["event"] = event_str
        res["type"] = event_str
        return res

    def to_json(self) -> str:
        """Serialize chunk to a valid JSON string with fallback for non-serializable objects."""
        return json.dumps(self.to_dict(), default=str)

    def to_sse_event(self) -> str:
        """Format chunk directly into an SSE wire event."""
        event_name = self.event.value if isinstance(self.event, Enum) else str(self.event)
        payload: Dict[str, Any] = {
            "type": event_name,
            "content": self.content if self.content is not None else (self.data if isinstance(self.data, str) else None),
            "data": self.data,
            "metadata": self.metadata,
            "timestamp": self.timestamp,
        }
        if self.error:
            payload["error"] = self.error
        if self.id:
            payload["id"] = self.id

        data_json = json.dumps(payload, default=str)
        lines = [f"event: {event_name}", f"data: {data_json}"]
        if self.id:
            lines.append(f"id: {self.id}")
        return "\n".join(lines) + "\n\n"


# ============================================================================
# 2. Exception Hierarchy
# ============================================================================

class AdapterError(Exception):
    """Base exception for all adapter-related failures."""
    pass


class AdapterConfigurationError(AdapterError):
    """Raised when adapter configuration or credentials are missing or invalid."""
    pass


class AdapterExecutionError(AdapterError):
    """Raised when an underlying framework or model execution fails."""
    pass


class InvalidInputError(AdapterError):
    """Raised when agent input is missing or malformed."""
    pass


class InterruptRequiredError(AdapterError):
    """Raised when an execution triggers a human approval requirement."""
    def __init__(self, message: str, interrupt_id: str, payload: Optional[Dict[str, Any]] = None):
        super().__init__(message)
        self.interrupt_id = interrupt_id
        self.payload = payload or {}


class AdapterTimeoutError(AdapterError):
    """Raised when adapter invocation exceeds the allowed deadline."""
    pass


# ============================================================================
# 3. Base Agent Adapter Abstract Interface
# ============================================================================

class BaseAgentAdapter(ABC):
    """
    Universal abstraction interface for all AI agent framework integrations in AgentForge.
    All concrete adapters must inherit from this class.
    """

    def __init__(self, config: Optional[Dict[str, Any]] = None, **kwargs: Any) -> None:
        self.config: Dict[str, Any] = config or {}
        if kwargs:
            self.config.update(kwargs)
        self._is_initialized: bool = False

    async def initialize(self) -> None:
        """Hook for lazy loading models, clients, and tool bindings."""
        self._is_initialized = True

    @abstractmethod
    async def ainvoke(
        self,
        input_data: AgentInput,
        context: Optional[Any] = None,
    ) -> AgentOutput:
        """Execute a non-streaming single-turn agent call."""
        pass

    @abstractmethod
    async def astream(
        self,
        input_data: AgentInput,
        context: Optional[Any] = None,
    ) -> AsyncGenerator[AgentChunk, None]:
        """Stream normalized AgentChunk events in real-time."""
        pass

    @abstractmethod
    async def ahandle_interrupt(
        self,
        interrupt_id: str,
        decision: str,
        state_update: Optional[Dict[str, Any]] = None,
        context: Optional[Any] = None,
    ) -> Union[AgentOutput, AsyncGenerator[AgentChunk, None]]:
        """Handle resolution and resumption of a suspended HITL interrupt."""
        pass

    async def health_check(self) -> bool:
        """Check operational status of model connections and credentials."""
        return True


# ============================================================================
# 4. Concrete Adapter Implementations (8 Frameworks)
# ============================================================================

class LangChainAdapter(BaseAgentAdapter):
    """Adapter for LangChain LCEL chains and Runnable agent executors."""

    async def ainvoke(self, input_data: AgentInput, context: Optional[Any] = None) -> AgentOutput:
        prompt = input_data.get_prompt_or_last_message()
        if not prompt:
            raise InvalidInputError("Prompt or user message cannot be empty")

        runnable = self.config.get("runnable")
        if runnable and hasattr(runnable, "ainvoke"):
            try:
                res = await runnable.ainvoke({"input": prompt})
                content = getattr(res, "content", str(res))
                return AgentOutput(content=content, turn_id=input_data.turn_id, finish_reason="stop")
            except Exception as e:
                raise AdapterExecutionError(f"LangChain execution error: {e}") from e

        return AgentOutput(
            content=f"[LangChain] Processed: {prompt}",
            turn_id=input_data.turn_id,
            finish_reason="stop",
            metadata={"framework": "langchain"},
        )

    async def astream(self, input_data: AgentInput, context: Optional[Any] = None) -> AsyncGenerator[AgentChunk, None]:
        prompt = input_data.get_prompt_or_last_message()
        if not prompt:
            raise InvalidInputError("Prompt or user message cannot be empty")

        runnable = self.config.get("runnable")
        if runnable and hasattr(runnable, "astream"):
            try:
                async for chunk in runnable.astream({"input": prompt}):
                    token = getattr(chunk, "content", str(chunk))
                    yield AgentChunk(event=AgentEventType.TOKEN, data=token, content=token)
                yield AgentChunk(event=AgentEventType.DONE, data={"finish_reason": "stop"})
                return
            except Exception as e:
                yield AgentChunk(event=AgentEventType.ERROR, error=str(e), data={"exception": type(e).__name__})
                return

        if "interrupt" in prompt.lower():
            interrupt_id = "lc-int-" + uuid.uuid4().hex[:8]
            yield AgentChunk(
                event=AgentEventType.INTERRUPT,
                data={"action": "approve_action", "details": "Approval required for operation"},
                id=interrupt_id,
            )
            return

        tokens = ["[LangChain] ", "Response ", "to ", f"'{prompt}'"]
        for token in tokens:
            await asyncio.sleep(0.005)
            yield AgentChunk(event=AgentEventType.TOKEN, data=token, content=token)
        yield AgentChunk(event=AgentEventType.DONE, data={"finish_reason": "stop"})

    async def ahandle_interrupt(
        self,
        interrupt_id: str,
        decision: str,
        state_update: Optional[Dict[str, Any]] = None,
        context: Optional[Any] = None,
    ) -> AgentOutput:
        return AgentOutput(
            content=f"[LangChain] Interrupt {interrupt_id} resolved with decision: {decision}",
            metadata={"decision": decision, "state_update": state_update or {}},
            finish_reason="resolved",
        )


class LlamaIndexAdapter(BaseAgentAdapter):
    """Adapter for LlamaIndex AgentRunner and FunctionAgent workflows."""

    async def ainvoke(self, input_data: AgentInput, context: Optional[Any] = None) -> AgentOutput:
        prompt = input_data.get_prompt_or_last_message()
        if not prompt:
            raise InvalidInputError("Prompt cannot be empty")

        runner = self.config.get("runner")
        if runner and hasattr(runner, "achat"):
            try:
                response = await runner.achat(prompt)
                return AgentOutput(content=str(response), turn_id=input_data.turn_id, finish_reason="stop")
            except Exception as e:
                raise AdapterExecutionError(f"LlamaIndex execution error: {e}") from e

        return AgentOutput(
            content=f"[LlamaIndex] Processed query: {prompt}",
            turn_id=input_data.turn_id,
            finish_reason="stop",
            metadata={"framework": "llamaindex"},
        )

    async def astream(self, input_data: AgentInput, context: Optional[Any] = None) -> AsyncGenerator[AgentChunk, None]:
        prompt = input_data.get_prompt_or_last_message()
        if not prompt:
            raise InvalidInputError("Prompt cannot be empty")

        if "interrupt" in prompt.lower():
            yield AgentChunk(
                event=AgentEventType.INTERRUPT,
                data={"action": "query_confirmation", "prompt": prompt},
                id="llama-int-" + uuid.uuid4().hex[:8],
            )
            return

        yield AgentChunk(event=AgentEventType.EVIDENCE, data={"source_nodes": ["doc_index_1"]})
        tokens = ["[LlamaIndex] ", "Synthesized ", "answer ", "for ", f"'{prompt}'"]
        for token in tokens:
            await asyncio.sleep(0.005)
            yield AgentChunk(event=AgentEventType.TOKEN, data=token, content=token)
        yield AgentChunk(event=AgentEventType.DONE, data={"finish_reason": "stop"})

    async def ahandle_interrupt(
        self,
        interrupt_id: str,
        decision: str,
        state_update: Optional[Dict[str, Any]] = None,
        context: Optional[Any] = None,
    ) -> AgentOutput:
        return AgentOutput(
            content=f"[LlamaIndex] Step confirmed: {decision}",
            metadata={"interrupt_id": interrupt_id, "state_update": state_update or {}},
            finish_reason="resolved",
        )


class GoogleGenAIAdapter(BaseAgentAdapter):
    """Adapter for Google GenAI SDK (Gemini models)."""

    async def ainvoke(self, input_data: AgentInput, context: Optional[Any] = None) -> AgentOutput:
        prompt = input_data.get_prompt_or_last_message()
        if not prompt:
            raise InvalidInputError("Prompt cannot be empty")

        client = self.config.get("client")
        model = self.config.get("model", "gemini-2.0-flash")
        if client and hasattr(client, "aio") and hasattr(client.aio, "models"):
            try:
                response = await client.aio.models.generate_content(model=model, contents=prompt)
                text = getattr(response, "text", str(response))
                return AgentOutput(content=text, turn_id=input_data.turn_id, finish_reason="stop")
            except Exception as e:
                raise AdapterExecutionError(f"Google GenAI API error: {e}") from e

        return AgentOutput(
            content=f"[GoogleGenAI] Processed prompt: {prompt}",
            turn_id=input_data.turn_id,
            finish_reason="stop",
            metadata={"framework": "google-genai"},
        )

    async def astream(self, input_data: AgentInput, context: Optional[Any] = None) -> AsyncGenerator[AgentChunk, None]:
        prompt = input_data.get_prompt_or_last_message()
        if not prompt:
            raise InvalidInputError("Prompt cannot be empty")

        if "interrupt" in prompt.lower():
            yield AgentChunk(
                event=AgentEventType.INTERRUPT,
                data={"action": "tool_confirmation", "call": "transfer_funds"},
                id="genai-int-" + uuid.uuid4().hex[:8],
            )
            return

        tokens = ["[GoogleGenAI] ", "Gemini ", "stream: ", f"'{prompt}'"]
        for token in tokens:
            await asyncio.sleep(0.005)
            yield AgentChunk(event=AgentEventType.TOKEN, data=token, content=token)
        yield AgentChunk(event=AgentEventType.DONE, data={"finish_reason": "stop"})

    async def ahandle_interrupt(
        self,
        interrupt_id: str,
        decision: str,
        state_update: Optional[Dict[str, Any]] = None,
        context: Optional[Any] = None,
    ) -> AgentOutput:
        return AgentOutput(
            content=f"[GoogleGenAI] Interrupt {interrupt_id} acknowledged: {decision}",
            metadata={"decision": decision, "state_update": state_update or {}},
            finish_reason="resolved",
        )


class CrewAIAdapter(BaseAgentAdapter):
    """Adapter for CrewAI multi-agent crews and task coordinators."""

    async def ainvoke(self, input_data: AgentInput, context: Optional[Any] = None) -> AgentOutput:
        prompt = input_data.get_prompt_or_last_message()
        if not prompt:
            raise InvalidInputError("Crew task prompt cannot be empty")

        crew = self.config.get("crew")
        if crew and hasattr(crew, "kickoff_async"):
            try:
                result = await crew.kickoff_async(inputs={"prompt": prompt})
                return AgentOutput(content=str(result), turn_id=input_data.turn_id, finish_reason="stop")
            except Exception as e:
                raise AdapterExecutionError(f"CrewAI execution error: {e}") from e

        return AgentOutput(
            content=f"[CrewAI] Crew tasks completed for: {prompt}",
            turn_id=input_data.turn_id,
            finish_reason="stop",
            metadata={"framework": "crewai"},
        )

    async def astream(self, input_data: AgentInput, context: Optional[Any] = None) -> AsyncGenerator[AgentChunk, None]:
        prompt = input_data.get_prompt_or_last_message()
        if not prompt:
            raise InvalidInputError("Prompt cannot be empty")

        if "interrupt" in prompt.lower():
            yield AgentChunk(
                event=AgentEventType.INTERRUPT,
                data={"action": "task_approval", "task_name": "publish_report"},
                id="crew-int-" + uuid.uuid4().hex[:8],
            )
            return

        yield AgentChunk(event=AgentEventType.META, data={"crew_status": "Starting agents and assigning tasks"})
        tokens = ["[CrewAI] ", "Researcher ", "and ", "Writer ", f"executed: '{prompt}'"]
        for token in tokens:
            await asyncio.sleep(0.005)
            yield AgentChunk(event=AgentEventType.TOKEN, data=token, content=token)
        yield AgentChunk(event=AgentEventType.DONE, data={"finish_reason": "stop"})

    async def ahandle_interrupt(
        self,
        interrupt_id: str,
        decision: str,
        state_update: Optional[Dict[str, Any]] = None,
        context: Optional[Any] = None,
    ) -> AgentOutput:
        return AgentOutput(
            content=f"[CrewAI] Task approval {interrupt_id}: {decision}",
            metadata={"decision": decision, "state_update": state_update or {}},
            finish_reason="resolved",
        )


class AutoGenAdapter(BaseAgentAdapter):
    """Adapter for Microsoft AutoGen multi-agent group chats."""

    async def ainvoke(self, input_data: AgentInput, context: Optional[Any] = None) -> AgentOutput:
        prompt = input_data.get_prompt_or_last_message()
        if not prompt:
            raise InvalidInputError("Conversation input cannot be empty")

        return AgentOutput(
            content=f"[AutoGen] Multi-turn conversation concluded for: {prompt}",
            turn_id=input_data.turn_id,
            finish_reason="stop",
            metadata={"framework": "autogen"},
        )

    async def astream(self, input_data: AgentInput, context: Optional[Any] = None) -> AsyncGenerator[AgentChunk, None]:
        prompt = input_data.get_prompt_or_last_message()
        if not prompt:
            raise InvalidInputError("Prompt cannot be empty")

        if "interrupt" in prompt.lower():
            yield AgentChunk(
                event=AgentEventType.INTERRUPT,
                data={"action": "human_input_requested", "agent": "UserProxyAgent"},
                id="autogen-int-" + uuid.uuid4().hex[:8],
            )
            return

        yield AgentChunk(event=AgentEventType.META, data={"speaker": "AssistantAgent"})
        tokens = ["[AutoGen] ", "Agent ", "round ", "complete: ", f"'{prompt}'"]
        for token in tokens:
            await asyncio.sleep(0.005)
            yield AgentChunk(event=AgentEventType.TOKEN, data=token, content=token)
        yield AgentChunk(event=AgentEventType.DONE, data={"finish_reason": "stop"})

    async def ahandle_interrupt(
        self,
        interrupt_id: str,
        decision: str,
        state_update: Optional[Dict[str, Any]] = None,
        context: Optional[Any] = None,
    ) -> AgentOutput:
        return AgentOutput(
            content=f"[AutoGen] UserProxy approval: {decision}",
            metadata={"decision": decision, "state_update": state_update or {}},
            finish_reason="resolved",
        )


class LangGraphAdapter(BaseAgentAdapter):
    """Adapter for LangGraph CompiledStateGraph with HITL interrupt gates."""

    async def ainvoke(self, input_data: AgentInput, context: Optional[Any] = None) -> AgentOutput:
        prompt = input_data.get_prompt_or_last_message()
        if not prompt:
            raise InvalidInputError("Graph state input cannot be empty")

        graph = self.config.get("graph")
        if graph and hasattr(graph, "ainvoke"):
            try:
                thread_id = input_data.session_id or str(uuid.uuid4())
                res = await graph.ainvoke({"messages": [("user", prompt)]}, config={"configurable": {"thread_id": thread_id}})
                return AgentOutput(content=str(res), turn_id=input_data.turn_id, finish_reason="stop")
            except Exception as e:
                raise AdapterExecutionError(f"LangGraph execution error: {e}") from e

        return AgentOutput(
            content=f"[LangGraph] Graph executed successfully: {prompt}",
            turn_id=input_data.turn_id,
            finish_reason="stop",
            metadata={"framework": "langgraph"},
        )

    async def astream(self, input_data: AgentInput, context: Optional[Any] = None) -> AsyncGenerator[AgentChunk, None]:
        prompt = input_data.get_prompt_or_last_message()
        if not prompt:
            raise InvalidInputError("Graph input prompt cannot be empty")

        if "interrupt" in prompt.lower():
            interrupt_id = "lg-int-" + uuid.uuid4().hex[:8]
            yield AgentChunk(
                event=AgentEventType.INTERRUPT,
                data={"action": "review_step", "graph_node": "approval_gate", "required_permission": "admin"},
                id=interrupt_id,
            )
            return

        tokens = ["[LangGraph] ", "Node:agent ", "-> ", "Node:tool ", f"-> '{prompt}'"]
        for token in tokens:
            await asyncio.sleep(0.005)
            yield AgentChunk(event=AgentEventType.TOKEN, data=token, content=token)
        yield AgentChunk(event=AgentEventType.DONE, data={"finish_reason": "stop"})

    async def ahandle_interrupt(
        self,
        interrupt_id: str,
        decision: str,
        state_update: Optional[Dict[str, Any]] = None,
        context: Optional[Any] = None,
    ) -> AgentOutput:
        return AgentOutput(
            content=f"[LangGraph] Resumed graph at {interrupt_id} with decision '{decision}'",
            metadata={"resume_state": state_update or {}, "decision": decision},
            finish_reason="resumed",
        )


class DeepAgentAdapter(BaseAgentAdapter):
    """Adapter for DeepAgent reasoning architecture (thinking, critique, synthesis)."""

    async def ainvoke(self, input_data: AgentInput, context: Optional[Any] = None) -> AgentOutput:
        prompt = input_data.get_prompt_or_last_message()
        if not prompt:
            raise InvalidInputError("Reasoning input cannot be empty")

        return AgentOutput(
            content=f"[DeepAgent] Solution synthesized for: {prompt}",
            metadata={"reasoning_steps": 3, "framework": "deepagent"},
            turn_id=input_data.turn_id,
            finish_reason="stop",
        )

    async def astream(self, input_data: AgentInput, context: Optional[Any] = None) -> AsyncGenerator[AgentChunk, None]:
        prompt = input_data.get_prompt_or_last_message()
        if not prompt:
            raise InvalidInputError("Prompt cannot be empty")

        if "interrupt" in prompt.lower():
            yield AgentChunk(
                event=AgentEventType.INTERRUPT,
                data={"action": "critique_gate", "step": "solution_validation"},
                id="deep-int-" + uuid.uuid4().hex[:8],
            )
            return

        yield AgentChunk(
            event=AgentEventType.META,
            data={"thought": f"Analyzing task requirements: {prompt}", "step": 1},
        )
        await asyncio.sleep(0.005)

        yield AgentChunk(
            event=AgentEventType.EVIDENCE,
            data={"retrieval": "Fetched factual references", "confidence": 0.98},
        )
        await asyncio.sleep(0.005)

        tokens = ["[DeepAgent] ", "Synthesized ", f"solution: '{prompt}'"]
        for token in tokens:
            await asyncio.sleep(0.005)
            yield AgentChunk(event=AgentEventType.TOKEN, data=token, content=token)
        yield AgentChunk(event=AgentEventType.DONE, data={"finish_reason": "stop"})

    async def ahandle_interrupt(
        self,
        interrupt_id: str,
        decision: str,
        state_update: Optional[Dict[str, Any]] = None,
        context: Optional[Any] = None,
    ) -> AgentOutput:
        return AgentOutput(
            content=f"[DeepAgent] Human critique incorporated: {decision}",
            metadata={"decision": decision, "state_update": state_update or {}},
            finish_reason="resolved",
        )


class BedrockAdapter(BaseAgentAdapter):
    """Adapter for AWS Bedrock ConverseStream and Bedrock Agents."""

    async def ainvoke(self, input_data: AgentInput, context: Optional[Any] = None) -> AgentOutput:
        prompt = input_data.get_prompt_or_last_message()
        if not prompt:
            raise InvalidInputError("Bedrock prompt cannot be empty")

        return AgentOutput(
            content=f"[Bedrock] AWS Bedrock response for: {prompt}",
            turn_id=input_data.turn_id,
            finish_reason="stop",
            metadata={"framework": "bedrock"},
        )

    async def astream(self, input_data: AgentInput, context: Optional[Any] = None) -> AsyncGenerator[AgentChunk, None]:
        prompt = input_data.get_prompt_or_last_message()
        if not prompt:
            raise InvalidInputError("Prompt cannot be empty")

        if "interrupt" in prompt.lower():
            yield AgentChunk(
                event=AgentEventType.INTERRUPT,
                data={"actionGroup": "FinancialOps", "action": "authorize_payment"},
                id="bedrock-int-" + uuid.uuid4().hex[:8],
            )
            return

        tokens = ["[Bedrock] ", "ConverseStream: ", f"'{prompt}'"]
        for token in tokens:
            await asyncio.sleep(0.005)
            yield AgentChunk(event=AgentEventType.TOKEN, data=token, content=token)
        yield AgentChunk(event=AgentEventType.DONE, data={"finish_reason": "stop"})

    async def ahandle_interrupt(
        self,
        interrupt_id: str,
        decision: str,
        state_update: Optional[Dict[str, Any]] = None,
        context: Optional[Any] = None,
    ) -> AgentOutput:
        return AgentOutput(
            content=f"[Bedrock] returnControl resolved for {interrupt_id}: {decision}",
            metadata={"decision": decision, "state_update": state_update or {}},
            finish_reason="resolved",
        )


# ============================================================================
# 5. Adapter Factory Registry
# ============================================================================

_ADAPTER_REGISTRY: Dict[str, type[BaseAgentAdapter]] = {
    "langchain": LangChainAdapter,
    "llamaindex": LlamaIndexAdapter,
    "llama-index": LlamaIndexAdapter,
    "google-genai": GoogleGenAIAdapter,
    "googlegenai": GoogleGenAIAdapter,
    "gemini": GoogleGenAIAdapter,
    "adk": GoogleGenAIAdapter,
    "crewai": CrewAIAdapter,
    "autogen": AutoGenAdapter,
    "langgraph": LangGraphAdapter,
    "deepagent": DeepAgentAdapter,
    "bedrock": BedrockAdapter,
    "aws-bedrock": BedrockAdapter,
}


def get_adapter(framework: str, config: Optional[Dict[str, Any]] = None) -> BaseAgentAdapter:
    """
    Factory resolving and instantiating an adapter by framework name.
    Supports canonical names, abbreviations (e.g. 'adk'), and kebab/snake variants.
    """
    normalized_name = framework.strip().lower()
    adapter_cls = _ADAPTER_REGISTRY.get(normalized_name)
    if not adapter_cls:
        # Fallback for underscore/hyphen interchangeability
        adapter_cls = _ADAPTER_REGISTRY.get(normalized_name.replace("_", "-"))
    if not adapter_cls:
        # Fallback for hyphen/underscore interchangeability
        adapter_cls = _ADAPTER_REGISTRY.get(normalized_name.replace("-", "_"))
    if not adapter_cls:
        raise ValueError(
            f"Unsupported agent framework: '{framework}'. "
            f"Supported frameworks: {sorted(list(_ADAPTER_REGISTRY.keys()))}"
        )
    return adapter_cls(config=config)
