apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ project_name }}-frontend
  labels:
    app: {{ project_name }}-frontend
    app.kubernetes.io/component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ project_name }}-frontend
  template:
    metadata:
      labels:
        app: {{ project_name }}-frontend
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: {{ project_name }}-frontend:v1.0.0
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ project_name }}-frontend
  labels:
    app: {{ project_name }}-frontend
    app.kubernetes.io/component: frontend
spec:
  selector:
    app: {{ project_name }}-frontend
  ports:
    - port: 80
      targetPort: 80
