apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ project_name }}-config
data:
  APP_ENV: "dev"
  JWT_ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  LDAP_ENABLED: "false"
  SAML_ENABLED: "false"
