apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ project_name }}-frontend
  namespace: ai-agents
  labels:
    app: {{ project_name }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ project_name }}-frontend
  template:
    metadata:
      labels:
        app: {{ project_name }}-frontend
    spec:
      containers:
        - name: frontend
          image: {{ project_name }}-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ project_name }}-frontend
  namespace: ai-agents
spec:
  selector:
    app: {{ project_name }}-frontend
  ports:
    - port: 80
      targetPort: 80
